<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.fuin</groupId>
		<artifactId>pom</artifactId>
		<version>2.0.0</version>
	</parent>

	<groupId>org.fuin.dsl.ddd</groupId>
	<artifactId>ddd-templates</artifactId>
	<version>0.2.0-SNAPSHOT</version>
	<packaging>jar</packaging>

	<description>Xtend based DDD/CQRS code generation templates for use with SrcGen4J</description>

	<scm>
		<url>https://github.com/fuinorg/ddd-templates/</url>
		<connection>scm:git:git://github.com/fuinorg/ddd-templates.git</connection>
		<developerConnection>scm:git:git@github.com:fuinorg/ddd-templates.git</developerConnection>
	</scm>

	<issueManagement>
		<system>GitHub Issues</system>
		<url>https://github.com/fuinorg/ddd-templates/issues</url>
	</issueManagement>

	<properties>
		<java.version>21</java.version>
		<maven.compiler.release>${java.version}</maven.compiler.release>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>

		<assertj-core.version>3.27.3</assertj-core.version>
		<ddd-4-java.version>0.8.0-SNAPSHOT</ddd-4-java.version>
		<ddd-cqrs-dsl.version>1.0.0-SNAPSHOT</ddd-cqrs-dsl.version>
		<equalsverifier.version>4.0.9</equalsverifier.version>
		<esc.version>0.10.0-SNAPSHOT</esc.version>
		<hibernate-core.version>6.6.11.Final</hibernate-core.version>
		<jakarta.enterprise.cdi-api.version>4.1.0</jakarta.enterprise.cdi-api.version>
		<jakarta.json.version>2.0.1</jakarta.json.version>
		<jakarta.validation-api.version>3.0.2</jakarta.validation-api.version>
		<jaxb-runtime.version>4.0.5</jaxb-runtime.version>
		<threeten-jaxb-core.version>2.2.0</threeten-jaxb-core.version>
		<jsr305.version>3.0.2</jsr305.version>
		<junit-jupiter.version>5.10.5</junit-jupiter.version>
		<objects4j.version>0.11.1-SNAPSHOT</objects4j.version>
		<org.eclipse.emf.ecore.change.version>2.16.0</org.eclipse.emf.ecore.change.version>
		<org.eclipse.emf.ecore.version>2.36.0</org.eclipse.emf.ecore.version>
		<srcgen4j-core.version>0.5.0-SNAPSHOT</srcgen4j-core.version>
		<units4j.version>0.12.0</units4j.version>
		<xtext.version>2.39.0</xtext.version>
		<yasson.version>3.0.4</yasson.version>
		
	</properties>

	<dependencies>

		<!-- compile -->

		<dependency>
			<groupId>org.fuin.dsl</groupId>
			<artifactId>ddd-cqrs-dsl</artifactId>
			<version>${ddd-cqrs-dsl.version}</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.xtend</groupId>
			<artifactId>org.eclipse.xtend.lib</artifactId>
			<version>${xtext.version}</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.xtend</groupId>
			<artifactId>org.eclipse.xtend.core</artifactId>
			<version>${xtext.version}</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore</artifactId>
			<version>${org.eclipse.emf.ecore.version}</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore.change</artifactId>
			<version>${org.eclipse.emf.ecore.change.version}</version>
		</dependency>

		<dependency>
			<groupId>org.fuin.srcgen4j</groupId>
			<artifactId>srcgen4j-core</artifactId>
			<version>${srcgen4j-core.version}</version>
		</dependency>

		<dependency>
			<groupId>org.fuin.objects4j</groupId>
			<artifactId>objects4j-core</artifactId>
			<version>${objects4j.version}</version>
		</dependency>

		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<version>${jakarta.validation-api.version}</version>
		</dependency>

		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>${jsr305.version}</version>
		</dependency>

		<!-- test -->

		<dependency>
			<groupId>org.fuin.esc</groupId>
			<artifactId>esc-spi</artifactId>
			<version>${esc.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit-jupiter.version}</version>
		</dependency>

		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>${assertj-core.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtext.testing</artifactId>
			<version>${xtext.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.fuin</groupId>
			<artifactId>units4j</artifactId>
			<version>${units4j.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<version>${jakarta.enterprise.cdi-api.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.fuin.ddd4j</groupId>
			<artifactId>ddd-4-java-core</artifactId>
			<version>${ddd-4-java.version}</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.fuin.ddd4j</groupId>
			<artifactId>ddd-4-java-jaxb</artifactId>
			<version>${ddd-4-java.version}</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.fuin.ddd4j</groupId>
			<artifactId>ddd-4-java-jsonb</artifactId>
			<version>${ddd-4-java.version}</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.fuin.ddd4j</groupId>
			<artifactId>ddd-4-java-esc</artifactId>
			<version>${ddd-4-java.version}</version>
			<scope>test</scope>
		</dependency>		

		<dependency>
			<groupId>org.hibernate.orm</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>${hibernate-core.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>jakarta.json</artifactId>
			<version>${jakarta.json.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.eclipse</groupId>
			<artifactId>yasson</artifactId>
			<version>${yasson.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>${jaxb-runtime.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
		    <groupId>nl.jqno.equalsverifier</groupId>
		    <artifactId>equalsverifier</artifactId>
		    <version>${equalsverifier.version}</version>
		    <scope>test</scope>
		</dependency>

		<dependency>
		    <groupId>io.github.threeten-jaxb</groupId>
		    <artifactId>threeten-jaxb-core</artifactId>
		    <version>${threeten-jaxb-core.version}</version>
		</dependency>

	</dependencies>

	<build>

		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>						
						    <doclint>none</doclint>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.6.0</version>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>${basedir}/src/main/xtend-gen</source>
							</sources>
							
						</configuration>
					</execution>
					<execution>
						<id>add-test-source</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-test-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>${basedir}/src/test/xtend-gen</source>
							</sources>
							
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.5.0</version>
				<configuration>
					<filesets>
						<fileset>
							<directory>${basedir}/src/main/xtend-gen</directory>
							<includes>
								<include>**</include>
							</includes>
							<excludes>
								<exclude>.gitignore</exclude>
							</excludes>
						</fileset>
						<fileset>
							<directory>${basedir}/src/test/xtend-gen</directory>
							<includes>
								<include>**</include>
							</includes>
							<excludes>
								<exclude>.gitignore</exclude>
							</excludes>
						</fileset>
					</filesets>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.eclipse.xtend</groupId>
				<artifactId>xtend-maven-plugin</artifactId>
				<version>${xtext.version}</version>
				<dependencies>
					<dependency>
						<groupId>org.assertj</groupId>
						<artifactId>assertj-core</artifactId>
						<version>3.27.3</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
							<goal>testCompile</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/src/main/xtend-gen</outputDirectory>
							<testOutputDirectory>${basedir}/src/test/xtend-gen</testOutputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
 
	</build>

</project>
